### PR TITLE
error call when connecting.

### PR DESCRIPTION
**Pull request by ignacio**
Hi. I made a mistake in my last pull request (issue #11).
When Redis.connect fails, it tries to call _client.error_ when _client_ does not yet exist.

This commit fixes that.

### CODE REVIEW

**Comment by nrk** [comment]
Uh, I was almost sure that there was a test for failed connections to a Redis server in the test suite, but it doesn't seem so or I would have spotted that bug. Thanks for fixing it, I will also add a test by tomorrow.

**Comment by ignacio** [comment]
Great, thank you.

**Comment by nrk** [comment]
So I ended up adding the [new test case](http://github.com/nrk/redis-lua/commit/90101f4e417643033ab4ece0ae94b04129315a1e) right away using a custom assertion :-) (I just love @norman's Telescope).

**Comment by ignacio** [comment]
Indeed, it is a great test tool.

**Comment by norman** [comment]
Thanks, guys! Haven't had much time to hack on my Lua projects lately, but with 5.2 right around the corner now, I think I may need to spend some time and make Telescope compatible.

**Pull request merged**
