### PR TITLE
queued_parsers during a transaction

### PR DESCRIPTION
**Pull request by slact**
It'd be useful to either have access to the table, or to be able to see the size of said table anytime during a transaction. Without this, it is impossible to write a full-fledged transaction merging function. I've added 
transaction_client:commands_queued(), but there's probably a cleaner way. What do you think?

### CODE REVIEW

**Comment by nrk** [comment]
Adding this feature does not pose any problem, but I can not imagine an actual use case for it and I am quite curious. Can you provide a real quick but concrete example so that I can better understand how this can be useful in practice?

**Comment by slact** [comment]
This is useful for transparently performing multiple transactions in one, like so: https://gist.github.com/776647 (note that that code's a bit untested, so if you see something that's off, it probably is.)

A transaction block for such a function might look like this: https://gist.github.com/776659

**Comment by nrk** [comment]
Oh right, I see. I'll start by merging your commit later, and I'll play a bit with your gist to see if I can get any additional idea.

**Comment by nrk** [comment]
OK, merged into master. Thanks!

**Pull request closed without merging**
