### PR TITLE
Allow users to pass a socket timeout when calling redis.connect. 

### PR DESCRIPTION
**Pull request by ezranuite**
We had issues with redis-lua hanging our web services because it had trouble connecting at times. The default timeout of 30 seconds was a real nightmare since our web workers should should be returning quickly.

To solve this issue we added the ability to pass a timeout into the connect call. This allows us to connect to redis in a non-blocking manner.

### CODE REVIEW

**Comment by nrk** [comment]
Thanks for the PR, all in all I do agree that having a `timeout` option is something desirable but I'm not convinced by the timeout mode chosen.

**Comment by ezranuite** [comment]
You could simplify that. It's just my poor Lua knowledge shining though :-)

**Comment by ezranuite** [comment]
On the topic of passing `t`.  My understanding from the docs is `b` only pertains to OS level blocking and `t` applies to the total time each call can block for.

**Comment by nrk** [comment]
Yes you were right @ezranuite, and @larubbio helped me noticing that I got them backwards ;-) Thanks!

**Pull request merged**
